apiVersion: apps/v1
kind: Deployment
metadata:
  name: webirc
  namespace: webirc
  labels:
    app: webirc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webirc
  template:
    metadata:
      labels:
        app: webirc
    spec:
      containers:
      - name: webirc
        image: ghcr.io/thelounge/thelounge:latest
        env:
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webirc-secret
                key: ADMIN_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/opt/thelounge
        lifecycle:
          postStart:
            exec:
              command:
                - "thelounge add ryzen --password $ADMIN_PASSWORD"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: webirc-data
